site:
  title: "#help"
  start_page: project-name::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://github.com/ircnet-com/antora-ui-ircnet/archive/refs/tags/v1.0.zip
    snapshot: true
